setMethod("initialize", "ParSnpCallSet",
          function(.Object, ...){
            .Object <- callNextMethod(.Object, ...)
            .Object$col <- c("lightblue", "red", "lightblue")
            .Object$ylab <- "genotype call"
            .Object
          })

setMethod("initialize", "ParSnpCopyNumberSet",
          function(.Object, ...){
            .Object <- callNextMethod(.Object, ...)
            .Object$ylab <- "copy number"
            .Object
          })

setMethod("initialize", "ParSnpSet",
          function(.Object, ...){
            .Object <- callNextMethod(.Object, ...)
            .Object$col <- c("lightblue", "red", "lightblue")
            .Object$bg <- c("lightblue", "red", "lightblue")            
            .Object$ylab <- "copy number"
	    .Object$legend.fill <- .Object$col
            .Object
          })


setMethod("initialize", "ParESet",
          function(.Object,
                   layout=TRUE,
                   col.axis="brown",
                   cex.main=1,
                   cex.axis=1,
                   cex.legend=1,
                   cex=2,
                   cex.lab=1,
                   pch=".",
                   col="black",
                   bg="white",
                   xaxs="r",
                   xaxt="s",
                   yaxs="r",
                   yaxt="s",
		   at=1:4,
                   lab=c(2, 5, 7), ##see par
                   adj=0,
                   bty="n",
                   ann=FALSE,
                   useLayout=TRUE,
                   mar=c(0.5, 0, 0.5, 0.2),
                   oma=c(4, 4, 4, 0.5),
                   las=1,
                   log="",
                   ylab="",
                   side.ylab=2,
                   outer.ylab=TRUE,
                   line.ylab=3,
                   cex.ylab=1,
                   xlab="Mb",
                   outer.xlab=TRUE,
                   side.xlab=1,
                   cex.xlab=1,
                   line.xlab=1,
                   outer.axis=TRUE,
                   line.axis=0,
                   main="",
		   add.centromere=TRUE,
                   col.centromere="bisque",
                   border.centromere="bisque",
                   xlim=NULL,
                   ylim=NULL,
                   one.ylim=TRUE,
                   add.cytoband=TRUE,
                   outer.cytoband=FALSE,
                   outer.cytoband.axis=FALSE,                   
                   label.cytoband=FALSE,
                   use.chromosome.size=FALSE, #for x-axis limits
                   label.chromosome=TRUE,
                   line.label.chromosome=2,
                   xaxis.side=1,
                   alternate.xaxis.side=FALSE,
                   mat=new("matrix", 1, 1),
                   heights=1,
                   widths=1,
                   respect=FALSE,
                   firstChromosome="1",
                   abline=FALSE,
                   abline.h=2,
                   abline.col="grey80",
                   abline.lty=1,
                   abline.lwd=1,
		   abline.v=NULL,
		   abline.v.col="grey20",
		   abline.v.lty=2,
		   abline.v.lwd=0.8,
		   legend=NULL,
		   legend.location="topright",
		   legend.bty="n",
		   legend.fill="white",
		   legend.pch=21,
                   border.prediction=grey(0.4),
                   legend.predict=NULL,
                   legend.location.predict="topleft",
		   legend.fill.predict=NULL,
		   col.predict=NULL,
		   height.predict=NULL,
		   cytoband.side=1,
                   ...){
            .Object@snpPar <- list(col.axis=col.axis,
                                   cex.main=cex.main,
                                   cex.axis=cex.axis,
                                   cex.legend=cex.legend,
                                   cex.lab=cex.lab,
                                   bty=bty,
                                   ann=ann,
                                   oma=oma,
                                   mar=mar,
                                   las=las,
                                   cex=cex,
                                   pch=pch,
                                   col=col,
                                   bg=bg,
                                   xaxs=xaxs,
                                   xaxt=xaxt,
                                   yaxt=yaxt,
				   at=at,
                                   yaxs=yaxs,
                                   lab=lab,
                                   adj=adj,
                                   log=log,
                                   xlab=xlab,
                                   side.xlab=side.xlab,
                                   outer.xlab=outer.xlab,
                                   cex.xlab=cex.xlab,
                                   line.xlab=line.xlab,
                                   ylab=ylab,
                                   side.ylab=side.ylab,
                                   outer.ylab=outer.ylab,
                                   cex.ylab=cex.ylab,
                                   line.ylab=line.ylab,
                                   main=main,
                                   xlim=xlim,
                                   ylim=ylim,
                                   col.centromere=col.centromere,
				   add.centromere=add.centromere,
                                   border.centromere=border.centromere,
                                   one.ylim=one.ylim,
                                   add.cytoband=add.cytoband,
                                   outer.cytoband=outer.cytoband,
                                   outer.cytoband.axis=outer.cytoband.axis,
                                   label.cytoband=label.cytoband,
                                   use.chromosome.size=use.chromosome.size,
                                   label.chromosome=label.chromosome,
                                   line.label.chromosome=line.label.chromosome,
                                   xaxis.side=xaxis.side,
                                   alternate.xaxis.side=alternate.xaxis.side,
                                   ##Arguments to layout()
                                   useLayout=useLayout,
                                   mat=mat,
                                   heights=heights,
                                   widths=widths,
                                   respect=respect,
                                   firstChromosome=firstChromosome,
                                   abline=abline,
                                   abline.h=abline.h,
                                   abline.col=abline.col,
                                   abline.lty=abline.lty,
                                   abline.lwd=abline.lwd,				   
				   abline.v=abline.v,
				   abline.v.col=abline.v.col,
				   abline.v.lwd=abline.v.lwd,
				   abline.v.lty=abline.v.lty,
				   legend=legend,
				   legend.location=legend.location,
				   legend.bty=legend.bty,
				   legend.fill=legend.fill,
				   legend.pch=legend.pch,
				   border.prediction=border.prediction,
				   legend.predict=legend.predict,
				   legend.location.predict=legend.location.predict,
				   legend.fill.predict=legend.fill.predict,
				   col.predict=col.predict,
				   height.predict=height.predict,
				   cytoband.side=cytoband.side)
            .Object
          })
